version: "3.9"
services:
  web:
    build: app/
    ports:
      - "5000:5000"
    volumes:
      - ./app:/code
    environment:
      FLASK_ENV: development
      FLASK_APP: flaskr
      FLASK_RUN_HOST: 0.0.0.0
  redis:
    image: "redis:alpine"
  mysql:
    image: "mysql:8.0.23"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
